SELECT 
U.GENERO,
COUNT(F.ID_CURSO) AS 'QTDE'
FROM USUARIOS AS U
LEFT JOIN CURSO_CONCLUIDO AS F ON U.ID_USUARIO=F.ID_USUARIO
WHERE F.ID_CURSO IS NOT NULL AND



SELECT 
U.GENERO,
COUNT(U.GENERO) AS 'QTDE'
FROM USUARIOS AS U
WHERE YEAR(U.DATA_ADMISSAO)>=2018 AND YEAR(U.DATA_ADMISSAO)<=2021
GROUP BY 
U.GENERO;

/* OU PODE SER EXECUTADO COM BETWEEN*/

SELECT 
U.GENERO,
COUNT(U.GENERO) AS 'QTDE'
FROM USUARIOS AS U
WHERE U.DATA_ADMISSAO BETWEEN '2018-01-01' AND '2021-12-31'
GROUP BY 
U.GENERO;

SELECT * FROM USUARIOS